#!/usr/local/bin/python

# Arguments todo:
# * parts to be installed: base, src, ports, lib32;
# * jail IP address;
# * jail name;
# * jail hostname;
# * internet inside;
# * service ssh;
# * service nginx.

import argparse

parser = argparse.ArgumentParser(description="Simple jail management tool", epilog="Visit http://github.com/xnicholas/lockup for more information.")

subparsers = parser.add_subparsers(help='action to be taken')

parser_create = subparsers.add_parser('create', help='creates jail')
parser_create.add_argument('hostname')
parser_create.add_argument('ip_address')
parser_create.add_argument('name')
parser_create.add_argument('-ars', '--allow-raw-sockets', action='store_const', const=1, help='allow raw sockets')
parser_create.add_argument('-sn', '--service-nginx', action='store_const', const=1, help='start nginx service')
parser_create.add_argument('-ss', '--service-sshd', action='store_const', const=1, help='start sshd service')
parser_create.set_defaults(cmd='create')

parser_remove = subparsers.add_parser('remove', help='removes jail')
parser_remove.add_argument('name')
parser_remove.set_defaults(cmd='remove')

parser_list = subparsers.add_parser('list', help='lists all jails')
parser_list.set_defaults(cmd='list')

args = vars(parser.parse_args())
